// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: command.proto

package pcb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StopCommand struct {
	Instruction          uint32   `protobuf:"varint,1,opt,name=instruction,proto3" json:"instruction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopCommand) Reset()         { *m = StopCommand{} }
func (m *StopCommand) String() string { return proto.CompactTextString(m) }
func (*StopCommand) ProtoMessage()    {}
func (*StopCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_213c0bb044472049, []int{0}
}
func (m *StopCommand) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StopCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StopCommand.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StopCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopCommand.Merge(m, src)
}
func (m *StopCommand) XXX_Size() int {
	return m.Size()
}
func (m *StopCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_StopCommand.DiscardUnknown(m)
}

var xxx_messageInfo_StopCommand proto.InternalMessageInfo

func (m *StopCommand) GetInstruction() uint32 {
	if m != nil {
		return m.Instruction
	}
	return 0
}

type StopReply struct {
	ReturnStatus         uint32   `protobuf:"varint,1,opt,name=ReturnStatus,proto3" json:"ReturnStatus,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=Content,proto3" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopReply) Reset()         { *m = StopReply{} }
func (m *StopReply) String() string { return proto.CompactTextString(m) }
func (*StopReply) ProtoMessage()    {}
func (*StopReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_213c0bb044472049, []int{1}
}
func (m *StopReply) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StopReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StopReply.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StopReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopReply.Merge(m, src)
}
func (m *StopReply) XXX_Size() int {
	return m.Size()
}
func (m *StopReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StopReply.DiscardUnknown(m)
}

var xxx_messageInfo_StopReply proto.InternalMessageInfo

func (m *StopReply) GetReturnStatus() uint32 {
	if m != nil {
		return m.ReturnStatus
	}
	return 0
}

func (m *StopReply) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type InfoAllCommand struct {
	Instruction          uint32   `protobuf:"varint,1,opt,name=Instruction,proto3" json:"Instruction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoAllCommand) Reset()         { *m = InfoAllCommand{} }
func (m *InfoAllCommand) String() string { return proto.CompactTextString(m) }
func (*InfoAllCommand) ProtoMessage()    {}
func (*InfoAllCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_213c0bb044472049, []int{2}
}
func (m *InfoAllCommand) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *InfoAllCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_InfoAllCommand.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *InfoAllCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoAllCommand.Merge(m, src)
}
func (m *InfoAllCommand) XXX_Size() int {
	return m.Size()
}
func (m *InfoAllCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoAllCommand.DiscardUnknown(m)
}

var xxx_messageInfo_InfoAllCommand proto.InternalMessageInfo

func (m *InfoAllCommand) GetInstruction() uint32 {
	if m != nil {
		return m.Instruction
	}
	return 0
}

type InfoAllReply struct {
	Dbtype               string   `protobuf:"bytes,1,opt,name=Dbtype,proto3" json:"Dbtype,omitempty"`
	Program              string   `protobuf:"bytes,2,opt,name=Program,proto3" json:"Program,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=Status,proto3" json:"Status,omitempty"`
	GroupID              string   `protobuf:"bytes,4,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
	Lag                  string   `protobuf:"bytes,5,opt,name=Lag,proto3" json:"Lag,omitempty"`
	TimeSinceChkpt       string   `protobuf:"bytes,6,opt,name=TimeSinceChkpt,proto3" json:"TimeSinceChkpt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoAllReply) Reset()         { *m = InfoAllReply{} }
func (m *InfoAllReply) String() string { return proto.CompactTextString(m) }
func (*InfoAllReply) ProtoMessage()    {}
func (*InfoAllReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_213c0bb044472049, []int{3}
}
func (m *InfoAllReply) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *InfoAllReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_InfoAllReply.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *InfoAllReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoAllReply.Merge(m, src)
}
func (m *InfoAllReply) XXX_Size() int {
	return m.Size()
}
func (m *InfoAllReply) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoAllReply.DiscardUnknown(m)
}

var xxx_messageInfo_InfoAllReply proto.InternalMessageInfo

func (m *InfoAllReply) GetDbtype() string {
	if m != nil {
		return m.Dbtype
	}
	return ""
}

func (m *InfoAllReply) GetProgram() string {
	if m != nil {
		return m.Program
	}
	return ""
}

func (m *InfoAllReply) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *InfoAllReply) GetGroupID() string {
	if m != nil {
		return m.GroupID
	}
	return ""
}

func (m *InfoAllReply) GetLag() string {
	if m != nil {
		return m.Lag
	}
	return ""
}

func (m *InfoAllReply) GetTimeSinceChkpt() string {
	if m != nil {
		return m.TimeSinceChkpt
	}
	return ""
}

type InfoDetailCommand struct {
	Instruction          uint32   `protobuf:"varint,1,opt,name=Instruction,proto3" json:"Instruction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoDetailCommand) Reset()         { *m = InfoDetailCommand{} }
func (m *InfoDetailCommand) String() string { return proto.CompactTextString(m) }
func (*InfoDetailCommand) ProtoMessage()    {}
func (*InfoDetailCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_213c0bb044472049, []int{4}
}
func (m *InfoDetailCommand) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *InfoDetailCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_InfoDetailCommand.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *InfoDetailCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoDetailCommand.Merge(m, src)
}
func (m *InfoDetailCommand) XXX_Size() int {
	return m.Size()
}
func (m *InfoDetailCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoDetailCommand.DiscardUnknown(m)
}

var xxx_messageInfo_InfoDetailCommand proto.InternalMessageInfo

func (m *InfoDetailCommand) GetInstruction() uint32 {
	if m != nil {
		return m.Instruction
	}
	return 0
}

type InfoDetailReply struct {
	Dbtype               string   `protobuf:"bytes,1,opt,name=Dbtype,proto3" json:"Dbtype,omitempty"`
	Program              string   `protobuf:"bytes,2,opt,name=Program,proto3" json:"Program,omitempty"`
	Groupid              string   `protobuf:"bytes,3,opt,name=Groupid,proto3" json:"Groupid,omitempty"`
	LastStarted          string   `protobuf:"bytes,4,opt,name=LastStarted,proto3" json:"LastStarted,omitempty"`
	Status               string   `protobuf:"bytes,5,opt,name=Status,proto3" json:"Status,omitempty"`
	FileNumber           string   `protobuf:"bytes,6,opt,name=FileNumber,proto3" json:"FileNumber,omitempty"`
	FileOffset           int64    `protobuf:"varint,7,opt,name=FileOffset,proto3" json:"FileOffset,omitempty"`
	LogNumber            string   `protobuf:"bytes,8,opt,name=LogNumber,proto3" json:"LogNumber,omitempty"`
	LogOffset            int64    `protobuf:"varint,9,opt,name=LogOffset,proto3" json:"LogOffset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoDetailReply) Reset()         { *m = InfoDetailReply{} }
func (m *InfoDetailReply) String() string { return proto.CompactTextString(m) }
func (*InfoDetailReply) ProtoMessage()    {}
func (*InfoDetailReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_213c0bb044472049, []int{5}
}
func (m *InfoDetailReply) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *InfoDetailReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_InfoDetailReply.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *InfoDetailReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoDetailReply.Merge(m, src)
}
func (m *InfoDetailReply) XXX_Size() int {
	return m.Size()
}
func (m *InfoDetailReply) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoDetailReply.DiscardUnknown(m)
}

var xxx_messageInfo_InfoDetailReply proto.InternalMessageInfo

func (m *InfoDetailReply) GetDbtype() string {
	if m != nil {
		return m.Dbtype
	}
	return ""
}

func (m *InfoDetailReply) GetProgram() string {
	if m != nil {
		return m.Program
	}
	return ""
}

func (m *InfoDetailReply) GetGroupid() string {
	if m != nil {
		return m.Groupid
	}
	return ""
}

func (m *InfoDetailReply) GetLastStarted() string {
	if m != nil {
		return m.LastStarted
	}
	return ""
}

func (m *InfoDetailReply) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *InfoDetailReply) GetFileNumber() string {
	if m != nil {
		return m.FileNumber
	}
	return ""
}

func (m *InfoDetailReply) GetFileOffset() int64 {
	if m != nil {
		return m.FileOffset
	}
	return 0
}

func (m *InfoDetailReply) GetLogNumber() string {
	if m != nil {
		return m.LogNumber
	}
	return ""
}

func (m *InfoDetailReply) GetLogOffset() int64 {
	if m != nil {
		return m.LogOffset
	}
	return 0
}

func init() {
	proto.RegisterType((*StopCommand)(nil), "pcb.StopCommand")
	proto.RegisterType((*StopReply)(nil), "pcb.StopReply")
	proto.RegisterType((*InfoAllCommand)(nil), "pcb.InfoAllCommand")
	proto.RegisterType((*InfoAllReply)(nil), "pcb.InfoAllReply")
	proto.RegisterType((*InfoDetailCommand)(nil), "pcb.InfoDetailCommand")
	proto.RegisterType((*InfoDetailReply)(nil), "pcb.InfoDetailReply")
}

func init() { proto.RegisterFile("command.proto", fileDescriptor_213c0bb044472049) }

var fileDescriptor_213c0bb044472049 = []byte{
	// 442 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0xbb, 0x4d, 0x9b, 0xe0, 0x69, 0x1b, 0xda, 0x05, 0x55, 0xab, 0x08, 0x59, 0x91, 0x0f,
	0x28, 0xe2, 0x90, 0x4a, 0xad, 0x38, 0xc1, 0x05, 0x12, 0x81, 0x22, 0x45, 0x80, 0x1c, 0x4e, 0xdc,
	0x6c, 0x67, 0x13, 0x2c, 0xe2, 0xdd, 0xd5, 0x66, 0x7c, 0xe8, 0x73, 0x70, 0xe1, 0x11, 0x38, 0xf0,
	0x20, 0x1c, 0x79, 0x04, 0x14, 0x5e, 0x04, 0xed, 0x7a, 0x5d, 0xaf, 0xc3, 0x89, 0xde, 0x3c, 0xdf,
	0xcc, 0xaf, 0x99, 0x7f, 0x76, 0x0c, 0x67, 0x99, 0x2c, 0x8a, 0x44, 0x2c, 0xc7, 0x4a, 0x4b, 0x94,
	0xb4, 0xa3, 0xb2, 0x34, 0xba, 0x82, 0x93, 0x05, 0x4a, 0x35, 0xa9, 0x32, 0x74, 0x08, 0x27, 0xb9,
	0xd8, 0xa2, 0x2e, 0x33, 0xcc, 0xa5, 0x60, 0x64, 0x48, 0x46, 0x67, 0xb1, 0x8f, 0xa2, 0x19, 0x04,
	0x46, 0x10, 0x73, 0xb5, 0xb9, 0xa5, 0x11, 0x9c, 0xc6, 0x1c, 0x4b, 0x2d, 0x16, 0x98, 0x60, 0xb9,
	0x75, 0xf5, 0x2d, 0x46, 0x19, 0xf4, 0x26, 0x52, 0x20, 0x17, 0xc8, 0x0e, 0x87, 0x64, 0x14, 0xc4,
	0x75, 0x18, 0x5d, 0x43, 0x7f, 0x26, 0x56, 0xf2, 0xd5, 0x66, 0xe3, 0xb5, 0x9f, 0xfd, 0xdb, 0xde,
	0x43, 0xd1, 0x0f, 0x02, 0xa7, 0x4e, 0x54, 0x8d, 0x70, 0x09, 0xdd, 0x69, 0x8a, 0xb7, 0x8a, 0xdb,
	0xea, 0x20, 0x76, 0x91, 0x69, 0xfb, 0x41, 0xcb, 0xb5, 0x4e, 0x8a, 0xba, 0xad, 0x0b, 0x8d, 0xc2,
	0x8d, 0xdb, 0xa9, 0x14, 0xcd, 0xa0, 0x6f, 0xb5, 0x2c, 0xd5, 0x6c, 0xca, 0x8e, 0x2a, 0x85, 0x0b,
	0xe9, 0x39, 0x74, 0xe6, 0xc9, 0x9a, 0x1d, 0x5b, 0x6a, 0x3e, 0xe9, 0x53, 0xe8, 0x7f, 0xcc, 0x0b,
	0xbe, 0xc8, 0x45, 0xc6, 0x27, 0x9f, 0xbf, 0x28, 0x64, 0x5d, 0x9b, 0xdc, 0xa3, 0xd1, 0x73, 0xb8,
	0x30, 0xd3, 0x4e, 0x39, 0x26, 0xf9, 0x7f, 0xb8, 0xfc, 0x7a, 0x08, 0x0f, 0x1b, 0xdd, 0x7d, 0x8d,
	0xd6, 0x86, 0xf2, 0xa5, 0x73, 0x5a, 0x87, 0x66, 0x82, 0x79, 0xb2, 0xc5, 0x05, 0x26, 0x1a, 0xf9,
	0xd2, 0xd9, 0xf5, 0x91, 0xb7, 0xa4, 0xe3, 0xd6, 0x92, 0x42, 0x80, 0x37, 0xf9, 0x86, 0xbf, 0x2b,
	0x8b, 0x94, 0x6b, 0x67, 0xda, 0x23, 0x75, 0xfe, 0xfd, 0x6a, 0xb5, 0xe5, 0xc8, 0x7a, 0x43, 0x32,
	0xea, 0xc4, 0x1e, 0xa1, 0x4f, 0x20, 0x98, 0xcb, 0xb5, 0x93, 0x3f, 0xb0, 0xf2, 0x06, 0xb8, 0xac,
	0x13, 0x07, 0x56, 0xdc, 0x80, 0xeb, 0xef, 0xc4, 0x18, 0xe2, 0x1c, 0xb9, 0xa6, 0xcf, 0xe0, 0xc8,
	0x9c, 0x21, 0x3d, 0x1f, 0xab, 0x2c, 0x1d, 0x7b, 0x27, 0x3c, 0xe8, 0xdf, 0x11, 0xbb, 0xb7, 0xe8,
	0x80, 0xde, 0x40, 0xcf, 0x9d, 0x0c, 0x7d, 0x64, 0x93, 0xed, 0xab, 0x1b, 0x5c, 0xf8, 0xb0, 0x16,
	0xbd, 0x04, 0x68, 0x5e, 0x80, 0x5e, 0xde, 0x95, 0xb4, 0x9e, 0x72, 0xf0, 0x78, 0x8f, 0x3b, 0xf5,
	0x6b, 0xf6, 0x73, 0x17, 0x92, 0x5f, 0xbb, 0x90, 0xfc, 0xde, 0x85, 0xe4, 0xdb, 0x9f, 0xf0, 0xe0,
	0x53, 0x77, 0x7c, 0xf5, 0x42, 0x65, 0x69, 0xda, 0xb5, 0x3f, 0xdf, 0xcd, 0xdf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xe7, 0xb8, 0xde, 0xee, 0x8d, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	Stop(ctx context.Context, in *StopCommand, opts ...grpc.CallOption) (*StopReply, error)
	InfoAll(ctx context.Context, in *InfoAllCommand, opts ...grpc.CallOption) (*InfoAllReply, error)
	InfoDetail(ctx context.Context, in *InfoDetailCommand, opts ...grpc.CallOption) (*InfoDetailReply, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) Stop(ctx context.Context, in *StopCommand, opts ...grpc.CallOption) (*StopReply, error) {
	out := new(StopReply)
	err := c.cc.Invoke(ctx, "/pcb.Greeter/Stop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) InfoAll(ctx context.Context, in *InfoAllCommand, opts ...grpc.CallOption) (*InfoAllReply, error) {
	out := new(InfoAllReply)
	err := c.cc.Invoke(ctx, "/pcb.Greeter/InfoAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) InfoDetail(ctx context.Context, in *InfoDetailCommand, opts ...grpc.CallOption) (*InfoDetailReply, error) {
	out := new(InfoDetailReply)
	err := c.cc.Invoke(ctx, "/pcb.Greeter/InfoDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	Stop(context.Context, *StopCommand) (*StopReply, error)
	InfoAll(context.Context, *InfoAllCommand) (*InfoAllReply, error)
	InfoDetail(context.Context, *InfoDetailCommand) (*InfoDetailReply, error)
}

// UnimplementedGreeterServer can be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (*UnimplementedGreeterServer) Stop(ctx context.Context, req *StopCommand) (*StopReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (*UnimplementedGreeterServer) InfoAll(ctx context.Context, req *InfoAllCommand) (*InfoAllReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InfoAll not implemented")
}
func (*UnimplementedGreeterServer) InfoDetail(ctx context.Context, req *InfoDetailCommand) (*InfoDetailReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InfoDetail not implemented")
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pcb.Greeter/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).Stop(ctx, req.(*StopCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_InfoAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoAllCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).InfoAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pcb.Greeter/InfoAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).InfoAll(ctx, req.(*InfoAllCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_InfoDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoDetailCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).InfoDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pcb.Greeter/InfoDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).InfoDetail(ctx, req.(*InfoDetailCommand))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pcb.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Stop",
			Handler:    _Greeter_Stop_Handler,
		},
		{
			MethodName: "InfoAll",
			Handler:    _Greeter_InfoAll_Handler,
		},
		{
			MethodName: "InfoDetail",
			Handler:    _Greeter_InfoDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "command.proto",
}

func (m *StopCommand) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StopCommand) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StopCommand) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Instruction != 0 {
		i = encodeVarintCommand(dAtA, i, uint64(m.Instruction))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *StopReply) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StopReply) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StopReply) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Content) > 0 {
		i -= len(m.Content)
		copy(dAtA[i:], m.Content)
		i = encodeVarintCommand(dAtA, i, uint64(len(m.Content)))
		i--
		dAtA[i] = 0x12
	}
	if m.ReturnStatus != 0 {
		i = encodeVarintCommand(dAtA, i, uint64(m.ReturnStatus))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *InfoAllCommand) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *InfoAllCommand) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *InfoAllCommand) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Instruction != 0 {
		i = encodeVarintCommand(dAtA, i, uint64(m.Instruction))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *InfoAllReply) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *InfoAllReply) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *InfoAllReply) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.TimeSinceChkpt) > 0 {
		i -= len(m.TimeSinceChkpt)
		copy(dAtA[i:], m.TimeSinceChkpt)
		i = encodeVarintCommand(dAtA, i, uint64(len(m.TimeSinceChkpt)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Lag) > 0 {
		i -= len(m.Lag)
		copy(dAtA[i:], m.Lag)
		i = encodeVarintCommand(dAtA, i, uint64(len(m.Lag)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.GroupID) > 0 {
		i -= len(m.GroupID)
		copy(dAtA[i:], m.GroupID)
		i = encodeVarintCommand(dAtA, i, uint64(len(m.GroupID)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintCommand(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Program) > 0 {
		i -= len(m.Program)
		copy(dAtA[i:], m.Program)
		i = encodeVarintCommand(dAtA, i, uint64(len(m.Program)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Dbtype) > 0 {
		i -= len(m.Dbtype)
		copy(dAtA[i:], m.Dbtype)
		i = encodeVarintCommand(dAtA, i, uint64(len(m.Dbtype)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *InfoDetailCommand) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *InfoDetailCommand) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *InfoDetailCommand) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Instruction != 0 {
		i = encodeVarintCommand(dAtA, i, uint64(m.Instruction))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *InfoDetailReply) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *InfoDetailReply) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *InfoDetailReply) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.LogOffset != 0 {
		i = encodeVarintCommand(dAtA, i, uint64(m.LogOffset))
		i--
		dAtA[i] = 0x48
	}
	if len(m.LogNumber) > 0 {
		i -= len(m.LogNumber)
		copy(dAtA[i:], m.LogNumber)
		i = encodeVarintCommand(dAtA, i, uint64(len(m.LogNumber)))
		i--
		dAtA[i] = 0x42
	}
	if m.FileOffset != 0 {
		i = encodeVarintCommand(dAtA, i, uint64(m.FileOffset))
		i--
		dAtA[i] = 0x38
	}
	if len(m.FileNumber) > 0 {
		i -= len(m.FileNumber)
		copy(dAtA[i:], m.FileNumber)
		i = encodeVarintCommand(dAtA, i, uint64(len(m.FileNumber)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintCommand(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.LastStarted) > 0 {
		i -= len(m.LastStarted)
		copy(dAtA[i:], m.LastStarted)
		i = encodeVarintCommand(dAtA, i, uint64(len(m.LastStarted)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Groupid) > 0 {
		i -= len(m.Groupid)
		copy(dAtA[i:], m.Groupid)
		i = encodeVarintCommand(dAtA, i, uint64(len(m.Groupid)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Program) > 0 {
		i -= len(m.Program)
		copy(dAtA[i:], m.Program)
		i = encodeVarintCommand(dAtA, i, uint64(len(m.Program)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Dbtype) > 0 {
		i -= len(m.Dbtype)
		copy(dAtA[i:], m.Dbtype)
		i = encodeVarintCommand(dAtA, i, uint64(len(m.Dbtype)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintCommand(dAtA []byte, offset int, v uint64) int {
	offset -= sovCommand(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *StopCommand) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Instruction != 0 {
		n += 1 + sovCommand(uint64(m.Instruction))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *StopReply) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ReturnStatus != 0 {
		n += 1 + sovCommand(uint64(m.ReturnStatus))
	}
	l = len(m.Content)
	if l > 0 {
		n += 1 + l + sovCommand(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *InfoAllCommand) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Instruction != 0 {
		n += 1 + sovCommand(uint64(m.Instruction))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *InfoAllReply) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Dbtype)
	if l > 0 {
		n += 1 + l + sovCommand(uint64(l))
	}
	l = len(m.Program)
	if l > 0 {
		n += 1 + l + sovCommand(uint64(l))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovCommand(uint64(l))
	}
	l = len(m.GroupID)
	if l > 0 {
		n += 1 + l + sovCommand(uint64(l))
	}
	l = len(m.Lag)
	if l > 0 {
		n += 1 + l + sovCommand(uint64(l))
	}
	l = len(m.TimeSinceChkpt)
	if l > 0 {
		n += 1 + l + sovCommand(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *InfoDetailCommand) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Instruction != 0 {
		n += 1 + sovCommand(uint64(m.Instruction))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *InfoDetailReply) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Dbtype)
	if l > 0 {
		n += 1 + l + sovCommand(uint64(l))
	}
	l = len(m.Program)
	if l > 0 {
		n += 1 + l + sovCommand(uint64(l))
	}
	l = len(m.Groupid)
	if l > 0 {
		n += 1 + l + sovCommand(uint64(l))
	}
	l = len(m.LastStarted)
	if l > 0 {
		n += 1 + l + sovCommand(uint64(l))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovCommand(uint64(l))
	}
	l = len(m.FileNumber)
	if l > 0 {
		n += 1 + l + sovCommand(uint64(l))
	}
	if m.FileOffset != 0 {
		n += 1 + sovCommand(uint64(m.FileOffset))
	}
	l = len(m.LogNumber)
	if l > 0 {
		n += 1 + l + sovCommand(uint64(l))
	}
	if m.LogOffset != 0 {
		n += 1 + sovCommand(uint64(m.LogOffset))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovCommand(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCommand(x uint64) (n int) {
	return sovCommand(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *StopCommand) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCommand
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StopCommand: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StopCommand: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Instruction", wireType)
			}
			m.Instruction = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommand
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Instruction |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCommand(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCommand
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StopReply) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCommand
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StopReply: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StopReply: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReturnStatus", wireType)
			}
			m.ReturnStatus = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommand
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReturnStatus |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Content", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommand
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCommand
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCommand
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Content = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCommand(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCommand
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *InfoAllCommand) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCommand
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: InfoAllCommand: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: InfoAllCommand: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Instruction", wireType)
			}
			m.Instruction = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommand
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Instruction |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCommand(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCommand
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *InfoAllReply) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCommand
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: InfoAllReply: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: InfoAllReply: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Dbtype", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommand
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCommand
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCommand
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Dbtype = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Program", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommand
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCommand
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCommand
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Program = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommand
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCommand
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCommand
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GroupID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommand
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCommand
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCommand
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GroupID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Lag", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommand
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCommand
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCommand
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Lag = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeSinceChkpt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommand
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCommand
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCommand
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TimeSinceChkpt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCommand(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCommand
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *InfoDetailCommand) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCommand
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: InfoDetailCommand: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: InfoDetailCommand: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Instruction", wireType)
			}
			m.Instruction = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommand
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Instruction |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCommand(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCommand
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *InfoDetailReply) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCommand
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: InfoDetailReply: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: InfoDetailReply: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Dbtype", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommand
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCommand
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCommand
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Dbtype = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Program", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommand
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCommand
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCommand
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Program = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Groupid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommand
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCommand
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCommand
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Groupid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastStarted", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommand
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCommand
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCommand
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LastStarted = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommand
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCommand
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCommand
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FileNumber", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommand
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCommand
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCommand
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FileNumber = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FileOffset", wireType)
			}
			m.FileOffset = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommand
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FileOffset |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LogNumber", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommand
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCommand
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCommand
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LogNumber = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LogOffset", wireType)
			}
			m.LogOffset = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommand
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LogOffset |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCommand(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCommand
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCommand(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCommand
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCommand
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCommand
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCommand
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCommand
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCommand
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCommand        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCommand          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCommand = fmt.Errorf("proto: unexpected end of group")
)
